name: Publish Artifacts

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Publish
      run: dotnet publish ./ADOBuildLight/ --configuration Release --output ./artifacts
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ado-build-light
        path: ./artifacts
