name: Publish Artifacts

# Explicit permissions needed so the release action can create a tag/release
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Publish
      run: dotnet publish ./ADOBuildLight/ --configuration Release --output ./artifacts
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ado-build-light
        path: ./artifacts
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2.3.4
      with:
        tag_name: v${{ github.run_number }}
        body: |
          Automated release for build ${{ github.run_number }}
        files: ./artifacts/*
